-- Update Chat Widget FAQs with Comprehensive Questions and Answers
-- This script updates existing FAQs or inserts new ones if they don't exist
-- Run this after the initial table creation script

-- Connect to the ELearning database
\c ELearning;

-- Clear existing FAQs (optional - comment out if you want to keep existing ones)
-- DELETE FROM "FAQs";
-- DELETE FROM "FAQCategories";

-- Update or Insert FAQ Categories
INSERT INTO "FAQCategories" ("Id", "Name", "Description", "Icon", "IsActive", "CreatedAt", "UpdatedAt") VALUES
(1, 'Platform', 'Information about AUNG platform and what we offer', 'school', true, NOW(), NOW()),
(2, 'Instructors', 'Questions about course instructors and teaching', 'people', true, NOW(), NOW()),
(3, 'Courses', 'Information about courses, pricing, and enrollment', 'menu_book', true, NOW(), NOW()),
(4, 'Learning', 'How to start learning and navigate the platform', 'play_circle', true, NOW(), NOW()),
(5, 'Payment', 'Payment methods, pricing, and billing questions', 'payment', true, NOW(), NOW())
ON CONFLICT ("Id") DO UPDATE SET
    "Name" = EXCLUDED."Name",
    "Description" = EXCLUDED."Description",
    "Icon" = EXCLUDED."Icon",
    "UpdatedAt" = NOW();

-- Keep existing FAQs and add new comprehensive ones
-- Note: We're not deleting existing FAQs to preserve previous data

-- Use INSERT with WHERE NOT EXISTS to avoid duplicates
-- This approach doesn't require a unique constraint

-- Insert comprehensive FAQs covering all required topics
-- Using WHERE NOT EXISTS to avoid duplicates if FAQs already exist
INSERT INTO "FAQs" ("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
SELECT * FROM (VALUES

-- 1. LEARNING PLATFORM INFORMATION (CategoryId = 1)
('What is AUNG?', 'AUNG (Advanced Upskilling & New Growth) is an online learning platform that provides high-quality courses across various fields including Programming, Web Development, Data Science, Design, and Business. We offer self-paced courses with expert instructors, interactive content, progress tracking, and certificates upon completion. Our mission is to make quality education accessible to everyone and help learners achieve advanced upskilling and new growth in their careers.', 1, 'what is aung, platform, learning platform, about us, who are you, what do you do, advanced upskilling, new growth', 10, true, NOW(), NOW()),
('What does AUNG offer?', 'AUNG (Advanced Upskilling & New Growth) offers comprehensive online courses with video lessons, assignments, quizzes, and downloadable materials. You can learn at your own pace, track your progress, earn certificates, and access course materials anytime. We also provide expert instructors, interactive content, and a supportive learning community to help you achieve your learning goals.', 1, 'what do you offer, services, features, what can I learn, aung offers', 10, true, NOW(), NOW()),
('Who can use AUNG?', 'AUNG (Advanced Upskilling & New Growth) is designed for anyone who wants to learn new skills or advance their career. Whether you are a beginner looking to start learning, a professional seeking to upgrade your skills, or someone exploring new interests, our platform welcomes learners of all levels who are committed to advanced upskilling and new growth.', 1, 'who can use, target audience, learners, students, who can learn', 9, true, NOW(), NOW()),

-- 2. ABOUT INSTRUCTORS (CategoryId = 2)
('Who are the instructors?', 'Our instructors are experienced professionals and experts in their respective fields. They include industry professionals, certified educators, and subject matter experts who bring real-world experience to their teaching. Each instructor is carefully selected based on their expertise, teaching ability, and commitment to student success.', 2, 'instructors, teachers, who teaches, who are instructors, about instructors', 10, true, NOW(), NOW()),
('What qualifications do instructors have?', 'Our instructors have extensive experience in their fields, including professional certifications, industry experience, and proven teaching abilities. Many hold advanced degrees and have years of practical experience. We ensure all instructors meet our high standards for quality education.', 2, 'instructor qualifications, teacher credentials, instructor experience', 9, true, NOW(), NOW()),
('How do I become an instructor?', 'If you are an expert in your field and passionate about teaching, you can apply to become an instructor. Contact us through our support channels or visit the instructor application page. We review applications based on expertise, teaching experience, and course proposals.', 2, 'become instructor, teach courses, instructor application, how to teach', 8, true, NOW(), NOW()),
('Can I contact instructors directly?', 'Yes! You can interact with instructors through course discussions, Q&A sections, and messaging features within enrolled courses. Instructors are committed to helping students succeed and regularly respond to questions and provide feedback.', 2, 'contact instructor, message instructor, instructor communication', 7, true, NOW(), NOW()),

-- 3. ABOUT COURSES - FREE OR PAID (CategoryId = 3)
('Are courses free or paid?', 'AUNG (Advanced Upskilling & New Growth) offers both free and paid courses. Free courses provide full access to course materials, lessons, and basic features. Paid courses may include additional content, premium features, certificates, and direct instructor support. Course pricing is clearly displayed on each course page.', 3, 'free courses, paid courses, course pricing, cost, price, free or paid', 10, true, NOW(), NOW()),
('What is the difference between free and paid courses?', 'Free courses give you access to all course materials and lessons. Paid courses may include additional benefits such as premium content, downloadable resources, certificates of completion, priority instructor support, and exclusive assignments. Both types allow you to learn at your own pace.', 3, 'difference free paid, free vs paid, what included', 10, true, NOW(), NOW()),
('What types of courses are available?', 'We offer courses in multiple categories including Programming (Python, JavaScript, Java, etc.), Web Development (Frontend, Backend, Full Stack), Data Science, UI/UX Design, Business, Marketing, and more. Courses range from beginner to advanced levels to suit all learners.', 3, 'course types, categories, what courses, available courses, course topics', 9, true, NOW(), NOW()),
('How long are the courses?', 'Course duration varies depending on the content and complexity. Most courses range from a few hours to several weeks of content. Since courses are self-paced, you can complete them at your own speed. The estimated duration is shown on each course page.', 3, 'course duration, how long, course length, time to complete', 8, true, NOW(), NOW()),
('Can I preview courses before enrolling?', 'Yes! Most courses offer free previews including course introduction, sample lessons, and course outline. You can browse course content, read instructor profiles, and check reviews before deciding to enroll.', 3, 'preview course, course preview, try before buy, sample', 8, true, NOW(), NOW()),

-- 4. HOW TO START LEARNING (CategoryId = 4)
('How do I start learning?', 'To start learning: 1) Create a free account by clicking "Register" in the top navigation, 2) Browse courses on the "Courses" page, 3) Select a course that interests you, 4) Click "Enroll" or "Start Learning", 5) Begin with the first lesson. It''s that simple!', 4, 'how to start, start learning, begin, get started, how to begin', 10, true, NOW(), NOW()),
('How do I create an account?', 'Click the "Register" button in the top navigation bar. Fill in your details including email address, first name, last name, and password. After registration, verify your email if required, then log in to start exploring and enrolling in courses.', 4, 'create account, register, sign up, account registration', 10, true, NOW(), NOW()),
('How do I enroll in a course?', 'Browse courses on the "Courses" page, click on a course to view details, and click the "Enroll" or "Start Learning" button. For paid courses, you''ll complete payment first. Once enrolled, the course appears in your "My Courses" section and you can start learning immediately.', 4, 'enroll, enrollment, join course, how to enroll, start course', 10, true, NOW(), NOW()),
('How do I navigate the website?', 'Use the top navigation bar to access: "Courses" to browse all courses, "Dashboard" for your learning hub, "My Courses" to see enrolled courses, and your profile menu for account settings. The homepage shows featured courses and learning resources.', 4, 'navigate, navigation, how to use, website navigation, menu', 9, true, NOW(), NOW()),
('What is the Dashboard?', 'The Dashboard is your personal learning hub showing enrolled courses, progress tracking, recent activity, upcoming assignments, achievements, and quick access to continue learning. It helps you stay organized and track your learning journey.', 4, 'dashboard, what is dashboard, learning hub, my dashboard', 9, true, NOW(), NOW()),
('Can I learn at my own pace?', 'Absolutely! All courses are self-paced, meaning you can learn whenever and wherever you want. There are no deadlines or fixed schedules. You can pause, rewind, and review lessons as many times as needed to fully understand the material.', 4, 'self-paced, own pace, flexible learning, schedule, timing', 9, true, NOW(), NOW()),
('How do I track my progress?', 'Your progress is automatically tracked as you complete lessons, assignments, and quizzes. Visit your Dashboard to see completion percentages, course progress, and achievements. Each course shows your progress bar and completed sections.', 4, 'track progress, progress tracking, completion, how far', 8, true, NOW(), NOW()),

-- 5. HOW TO DO PAYMENT (CategoryId = 5)
('How do I pay for courses?', 'To pay for a course: 1) Select a paid course and click "Enroll", 2) You''ll be redirected to the payment page, 3) Choose your payment method (credit card, debit card, or other available options), 4) Enter payment details securely, 5) Complete the transaction. Once payment is confirmed, you''ll have immediate access to the course.', 5, 'how to pay, payment, pay for course, payment method, how to purchase', 10, true, NOW(), NOW()),
('What payment methods are accepted?', 'We accept major credit cards (Visa, MasterCard, American Express), debit cards, and other secure payment methods. All payments are processed through secure payment gateways to ensure your financial information is protected. Payment options are displayed during checkout.', 5, 'payment methods, credit card, debit card, payment options, how to pay', 10, true, NOW(), NOW()),
('Is payment secure?', 'Yes, all payments are processed through secure, encrypted payment gateways. We use industry-standard security measures to protect your financial information. We never store your full credit card details on our servers.', 5, 'secure payment, payment security, safe, secure, protection', 9, true, NOW(), NOW()),
('What is the refund policy?', 'We offer a refund policy for paid courses. If you are not satisfied with a course within the specified refund period (usually 30 days), you can request a refund through your account settings or by contacting support. Refunds are processed to your original payment method.', 5, 'refund, refund policy, money back, return, cancel', 9, true, NOW(), NOW()),
('Are there any discounts or promotions?', 'Yes! We regularly offer discounts, promotions, and special deals on courses. Check our homepage, newsletter, or follow us on social media to stay updated on current offers. Some courses may also have early-bird pricing or bundle discounts.', 5, 'discount, promotion, sale, special offer, coupon, deal', 8, true, NOW(), NOW()),
('Can I get a certificate?', 'Yes! Upon successful completion of a course, you will receive a certificate of completion. Certificates are automatically generated and can be downloaded from your Dashboard. Some free courses also offer certificates, while paid courses typically include verified certificates.', 5, 'certificate, certification, completion certificate, certificate of completion', 8, true, NOW(), NOW())
) AS new_faqs("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
WHERE NOT EXISTS (
    SELECT 1 FROM "FAQs" 
    WHERE LOWER(TRIM("Question")) = LOWER(TRIM(new_faqs."Question"))
);

-- Add additional comprehensive FAQs covering all possible user questions
INSERT INTO "FAQs" ("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
SELECT * FROM (VALUES

-- Additional Platform Questions
('Tell me about AUNG', 'AUNG (Advanced Upskilling & New Growth) is your gateway to professional development and career advancement. We provide comprehensive online courses designed to help you acquire new skills, upskill your existing knowledge, and achieve new growth in your career. Our platform features expert instructors, interactive learning materials, and flexible self-paced courses.', 1, 'tell me about, about aung, information, platform info', 9, true, NOW(), NOW()),
('What is Advanced Upskilling & New Growth?', 'Advanced Upskilling & New Growth (AUNG) is our learning platform dedicated to helping professionals enhance their skills and advance their careers. We focus on providing high-quality, practical courses that enable learners to upskill effectively and achieve meaningful career growth.', 1, 'advanced upskilling, new growth, what is, platform meaning', 9, true, NOW(), NOW()),
('Who are you?', 'I am AUNG''s virtual assistant, here to help you learn about our platform, courses, instructors, and services. AUNG (Advanced Upskilling & New Growth) is an online learning platform offering courses across Programming, Web Development, Data Science, Design, and Business. How can I assist you today?', 1, 'who are you, chatbot, assistant, help', 10, true, NOW(), NOW()),
('What can I learn on AUNG?', 'On AUNG, you can learn a wide variety of skills including Programming languages (Python, JavaScript, Java, C++, etc.), Web Development (Frontend, Backend, Full Stack), Data Science and Analytics, UI/UX Design, Business and Marketing, Digital Skills, and much more. Our courses range from beginner to advanced levels.', 1, 'what can I learn, learn, courses available, skills', 9, true, NOW(), NOW()),
('Is AUNG free?', 'AUNG offers both free and paid courses. You can create a free account and access free courses immediately. Paid courses offer additional features like certificates, premium content, and direct instructor support. Course pricing is clearly displayed on each course page.', 1, 'is aung free, free platform, cost, pricing', 8, true, NOW(), NOW()),

-- Additional Instructor Questions
('Who teaches the courses?', 'Our courses are taught by experienced professionals and industry experts. Our instructors include certified educators, industry professionals, and subject matter experts who bring years of real-world experience to their teaching. Each instructor is carefully vetted to ensure high-quality education.', 2, 'who teaches, teachers, course instructors, who are teachers', 9, true, NOW(), NOW()),
('Are instructors qualified?', 'Absolutely! All our instructors are highly qualified professionals with extensive experience in their fields. They hold professional certifications, industry experience, and proven teaching abilities. Many have advanced degrees and years of practical experience. We maintain high standards for instructor selection.', 2, 'instructors qualified, teacher qualifications, expert instructors', 8, true, NOW(), NOW()),
('Can I see instructor profiles?', 'Yes! You can view instructor profiles on each course page. Instructor profiles include their background, qualifications, experience, and other courses they teach. This helps you make informed decisions about which courses to enroll in.', 2, 'instructor profiles, teacher info, instructor background', 7, true, NOW(), NOW()),
('Do instructors provide support?', 'Yes! Instructors are actively involved in their courses and provide support through course discussions, Q&A sections, and direct messaging. They respond to questions, provide feedback on assignments, and help students succeed in their learning journey.', 2, 'instructor support, teacher help, instructor assistance', 8, true, NOW(), NOW()),

-- Additional Course Questions
('How much do courses cost?', 'Course prices vary depending on the course content and features. We offer both free courses and paid courses. Free courses provide full access to materials, while paid courses may include certificates, premium content, and instructor support. Each course page clearly displays its price.', 3, 'course cost, course price, how much, pricing, fees', 10, true, NOW(), NOW()),
('Are there free courses?', 'Yes! AUNG offers many free courses that provide full access to course materials, video lessons, and basic features. Free courses are a great way to start learning without any cost. You can browse free courses on our Courses page.', 3, 'free courses, free, no cost, free learning', 10, true, NOW(), NOW()),
('What course categories are available?', 'We offer courses in multiple categories including Programming (Python, JavaScript, Java, C++, etc.), Web Development (Frontend, Backend, Full Stack), Data Science and Analytics, UI/UX Design, Business and Entrepreneurship, Marketing, Digital Skills, and many more specialized topics.', 3, 'categories, course types, subjects, topics available', 9, true, NOW(), NOW()),
('What level are the courses?', 'Our courses are available at different levels: Beginner (for those new to the topic), Intermediate (for those with some knowledge), and Advanced (for experienced learners). Each course page indicates its difficulty level so you can choose courses appropriate for your skill level.', 3, 'course level, difficulty, beginner, intermediate, advanced', 8, true, NOW(), NOW()),
('Can I access courses on mobile?', 'Yes! AUNG is fully responsive and works on mobile devices, tablets, and desktops. You can access your courses, watch videos, complete assignments, and track your progress from any device with an internet connection.', 3, 'mobile, phone, tablet, device, access mobile', 8, true, NOW(), NOW()),
('Do courses have videos?', 'Yes! Most courses include video lessons as the primary learning format. Videos are supplemented with text materials, assignments, quizzes, and downloadable resources to provide a comprehensive learning experience.', 3, 'videos, video lessons, course videos, multimedia', 7, true, NOW(), NOW()),
('Are there assignments in courses?', 'Yes! Many courses include assignments and projects to help you practice what you learn. Assignments are designed to reinforce concepts and provide hands-on experience. Some courses also include quizzes to test your understanding.', 3, 'assignments, projects, exercises, practice, quizzes', 7, true, NOW(), NOW()),
('Can I download course materials?', 'Depending on the course, you may be able to download course materials such as PDFs, code files, templates, and other resources. Download availability varies by course and is typically available for paid courses or as specified on the course page.', 3, 'download, materials, resources, files, pdf', 7, true, NOW(), NOW()),

-- Additional Learning Questions
('How do I sign up?', 'To sign up: 1) Click the "Register" button in the top navigation bar, 2) Fill in your email, first name, last name, and password, 3) Complete registration, 4) Verify your email if required, 5) Log in and start exploring courses!', 4, 'sign up, register, create account, join, signup', 10, true, NOW(), NOW()),
('Do I need to create an account?', 'Yes, you need to create a free account to enroll in courses and track your progress. Registration is quick and free. Once registered, you can browse courses, enroll in free courses immediately, and purchase paid courses.', 4, 'need account, account required, registration required', 9, true, NOW(), NOW()),
('How do I find courses?', 'You can find courses by: 1) Browsing the "Courses" page, 2) Using the search bar to search by keyword, 3) Filtering by category, level, or price, 4) Viewing featured courses on the homepage. Popular courses are also highlighted for easy discovery.', 4, 'find courses, search courses, browse courses, discover', 9, true, NOW(), NOW()),
('What happens after I enroll?', 'After enrolling: 1) The course appears in your "My Courses" section, 2) You can start learning immediately by accessing course materials, 3) Your progress is automatically tracked, 4) You can complete lessons, assignments, and quizzes at your own pace, 5) Upon completion, you may receive a certificate.', 4, 'after enroll, what next, enrolled, course access', 9, true, NOW(), NOW()),
('Can I take multiple courses?', 'Absolutely! You can enroll in as many courses as you want, both free and paid. There is no limit to the number of courses you can take. You can learn multiple skills simultaneously and switch between courses as needed.', 4, 'multiple courses, several courses, many courses, multiple enrollments', 8, true, NOW(), NOW()),
('How do I access my courses?', 'To access your enrolled courses: 1) Log in to your account, 2) Click on "My Courses" in the navigation menu, 3) Select the course you want to continue, 4) You can also access courses from your Dashboard. All your enrolled courses are saved in your account.', 4, 'access courses, my courses, enrolled courses, course access', 9, true, NOW(), NOW()),
('Can I pause and resume courses?', 'Yes! Since all courses are self-paced, you can pause at any time and resume whenever you want. Your progress is saved automatically, so you can pick up exactly where you left off. There are no deadlines or time limits.', 4, 'pause, resume, stop, continue, break', 8, true, NOW(), NOW()),
('How do I complete a course?', 'To complete a course: 1) Watch all video lessons, 2) Complete assignments and quizzes, 3) Finish all course materials, 4) Meet any completion requirements specified by the course. Once completed, you may receive a certificate if the course offers one.', 4, 'complete course, finish course, course completion, done', 8, true, NOW(), NOW()),
('What if I need help while learning?', 'If you need help: 1) Use the course Q&A section to ask questions, 2) Contact the instructor through course messaging, 3) Participate in course discussions with other students, 4) Use this chat widget for general platform questions, 5) Contact our support team for technical issues.', 4, 'help, support, assistance, stuck, problem', 8, true, NOW(), NOW()),
('Can I learn offline?', 'Currently, courses require an internet connection to access. However, some courses may allow you to download materials for offline reference. Video lessons typically require an online connection for streaming.', 4, 'offline, without internet, download, offline learning', 7, true, NOW(), NOW()),

-- Additional Payment Questions
('How do I purchase a course?', 'To purchase a course: 1) Browse and select a paid course, 2) Click "Enroll" or "Buy Now", 3) You''ll be redirected to the secure payment page, 4) Choose your payment method, 5) Enter payment details, 6) Complete the purchase. You''ll have immediate access after payment confirmation.', 5, 'purchase, buy course, buy, purchase course, checkout', 10, true, NOW(), NOW()),
('What credit cards do you accept?', 'We accept all major credit cards including Visa, MasterCard, American Express, and Discover. We also accept debit cards and other secure payment methods. All accepted payment methods are displayed during checkout.', 5, 'credit card, visa, mastercard, amex, card types', 9, true, NOW(), NOW()),
('Is my payment information safe?', 'Yes! We use industry-standard encryption and secure payment gateways to protect your financial information. We never store your full credit card details on our servers. All transactions are processed through trusted, PCI-compliant payment processors.', 5, 'safe, secure, payment security, protect, secure payment', 9, true, NOW(), NOW()),
('Can I get a refund?', 'Yes, we offer refunds for paid courses. If you are not satisfied with a course within the refund period (typically 30 days), you can request a refund through your account settings or by contacting support. Refunds are processed to your original payment method.', 5, 'refund, money back, return, cancel purchase, refund policy', 9, true, NOW(), NOW()),
('How long is the refund period?', 'The refund period is typically 30 days from the date of purchase. However, specific refund terms may vary by course. Check the course page or contact support for exact refund policy details for a specific course.', 5, 'refund period, refund time, how long refund', 8, true, NOW(), NOW()),
('Do you offer payment plans?', 'Payment options vary by course. Some courses may offer payment plans or installment options. Check the course page for available payment options. For specific payment plan inquiries, please contact our support team.', 5, 'payment plan, installments, monthly payment, split payment', 7, true, NOW(), NOW()),
('Are there student discounts?', 'We occasionally offer discounts and promotions including student discounts, early-bird pricing, and bundle deals. Check our homepage, newsletter, or follow us on social media to stay updated on current offers and discount codes.', 5, 'student discount, discount code, promo code, coupon, special offer', 8, true, NOW(), NOW()),
('Can I gift a course?', 'Yes! You can purchase courses as gifts for others. During checkout, you''ll have the option to gift the course to someone else. The recipient will receive access instructions via email.', 5, 'gift, gift course, present, buy for someone', 7, true, NOW(), NOW()),
('What currency do you accept?', 'We accept payments in multiple currencies. The currency displayed depends on your location. Prices are shown in your local currency when available, or in USD. Payment processing supports international transactions.', 5, 'currency, payment currency, usd, local currency', 7, true, NOW(), NOW()),

-- General/Other Questions
('How do I contact support?', 'You can contact our support team through: 1) This chat widget for immediate assistance, 2) Email support (check the footer for contact information), 3) Support tickets through your account dashboard. We aim to respond within 24-48 hours.', 1, 'contact support, help, customer service, support team', 8, true, NOW(), NOW()),
('Is there a mobile app?', 'AUNG is accessible through web browsers on all devices including mobile phones and tablets. We are optimized for mobile use, so you can access all features through your mobile browser. A dedicated mobile app may be available in the future.', 1, 'mobile app, app, application, phone app', 7, true, NOW(), NOW()),
('Can I share my certificate?', 'Yes! You can download your certificate and share it on LinkedIn, social media, or include it in your resume. Certificates are a great way to showcase your achievements and skills to employers and colleagues.', 5, 'share certificate, certificate sharing, linkedin, social media', 7, true, NOW(), NOW()),
('Are courses updated regularly?', 'Yes! Instructors regularly update course content to keep it current with industry trends and best practices. You''ll have access to updated materials for courses you''re enrolled in, ensuring you learn the most relevant information.', 3, 'course updates, updated content, latest, current', 7, true, NOW(), NOW()),
('Can I become an instructor?', 'Yes! If you have expertise in a field and are passionate about teaching, you can apply to become an instructor. Contact us through support channels or visit our instructor application page. We review applications based on expertise, teaching experience, and course proposals.', 2, 'become instructor, teach, instructor application, apply', 8, true, NOW(), NOW())
) AS new_faqs("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
WHERE NOT EXISTS (
    SELECT 1 FROM "FAQs" 
    WHERE LOWER(TRIM("Question")) = LOWER(TRIM(new_faqs."Question"))
);

-- Update existing FAQs with new information if they exist
UPDATE "FAQs" f
SET 
    "Answer" = new_data."Answer",
    "CategoryId" = new_data."CategoryId",
    "Keywords" = new_data."Keywords",
    "Priority" = new_data."Priority",
    "UpdatedAt" = NOW()
FROM (VALUES
('What is AUNG?', 'AUNG (Advanced Upskilling & New Growth) is an online learning platform that provides high-quality courses across various fields including Programming, Web Development, Data Science, Design, and Business. We offer self-paced courses with expert instructors, interactive content, progress tracking, and certificates upon completion. Our mission is to make quality education accessible to everyone and help learners achieve advanced upskilling and new growth in their careers.', 1, 'what is aung, platform, learning platform, about us, who are you, what do you do, advanced upskilling, new growth', 10),
('What does AUNG offer?', 'AUNG (Advanced Upskilling & New Growth) offers comprehensive online courses with video lessons, assignments, quizzes, and downloadable materials. You can learn at your own pace, track your progress, earn certificates, and access course materials anytime. We also provide expert instructors, interactive content, and a supportive learning community to help you achieve your learning goals.', 1, 'what do you offer, services, features, what can I learn, aung offers', 10),
('Who can use AUNG?', 'AUNG (Advanced Upskilling & New Growth) is designed for anyone who wants to learn new skills or advance their career. Whether you are a beginner looking to start learning, a professional seeking to upgrade your skills, or someone exploring new interests, our platform welcomes learners of all levels who are committed to advanced upskilling and new growth.', 1, 'who can use, target audience, learners, students, who can learn', 9),
('Who are the instructors?', 'Our instructors are experienced professionals and experts in their respective fields. They include industry professionals, certified educators, and subject matter experts who bring real-world experience to their teaching. Each instructor is carefully selected based on their expertise, teaching ability, and commitment to student success.', 2, 'instructors, teachers, who teaches, who are instructors, about instructors', 10),
('Are courses free or paid?', 'AUNG (Advanced Upskilling & New Growth) offers both free and paid courses. Free courses provide full access to course materials, lessons, and basic features. Paid courses may include additional content, premium features, certificates, and direct instructor support. Course pricing is clearly displayed on each course page.', 3, 'free courses, paid courses, course pricing, cost, price, free or paid', 10),
('How do I start learning?', 'To start learning: 1) Create a free account by clicking "Register" in the top navigation, 2) Browse courses on the "Courses" page, 3) Select a course that interests you, 4) Click "Enroll" or "Start Learning", 5) Begin with the first lesson. It''s that simple!', 4, 'how to start, start learning, begin, get started, how to begin', 10),
('How do I pay for courses?', 'To pay for a course: 1) Select a paid course and click "Enroll", 2) You''ll be redirected to the payment page, 3) Choose your payment method (credit card, debit card, or other available options), 4) Enter payment details securely, 5) Complete the transaction. Once payment is confirmed, you''ll have immediate access to the course.', 5, 'how to pay, payment, pay for course, payment method, how to purchase', 10)
) AS new_data("Question", "Answer", "CategoryId", "Keywords", "Priority")
WHERE LOWER(TRIM(f."Question")) = LOWER(TRIM(new_data."Question"));
