-- Add Additional FAQ Categories and Comprehensive FAQs
-- This script adds new FAQ categories and their corresponding FAQs
-- Run this after the initial FAQ setup scripts

-- Connect to the ELearning database
\c ELearning;

-- Additional FAQ Categories
INSERT INTO "FAQCategories" ("Id", "Name", "Description", "Icon", "IsActive", "CreatedAt", "UpdatedAt") VALUES
(6, 'Account', 'Account registration, login, and profile management', 'person', true, NOW(), NOW()),
(7, 'Certificates', 'Certificates, verification, and sharing', 'verified', true, NOW(), NOW()),
(8, 'Technical', 'Technical issues, bugs, and troubleshooting', 'build', true, NOW(), NOW()),
(9, 'Access & Devices', 'Device compatibility and browser support', 'devices', true, NOW(), NOW()),
(10, 'Career & Jobs', 'Career benefits, jobs, and skill outcomes', 'work', true, NOW(), NOW()),
(11, 'Community', 'Community, discussions, and networking', 'forum', true, NOW(), NOW()),
(12, 'Legal & Privacy', 'Privacy, data protection, and terms', 'policy', true, NOW(), NOW()),
(13, 'Introduction', 'Welcome messages and getting started with the chat', 'waving_hand', true, NOW(), NOW()),
(14, 'Conclusion', 'Ending chat and farewell messages', 'exit_to_app', true, NOW(), NOW())
ON CONFLICT ("Id") DO UPDATE SET
    "Name" = EXCLUDED."Name",
    "Description" = EXCLUDED."Description",
    "Icon" = EXCLUDED."Icon",
    "UpdatedAt" = NOW();

-- Insert comprehensive FAQs for new categories
INSERT INTO "FAQs" ("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
SELECT * FROM (VALUES

-- 6. ACCOUNT (CategoryId = 6)
('How do I reset my password?', 'To reset your password: 1) Click "Login" in the navigation bar, 2) Click "Forgot Password" link, 3) Enter your email address, 4) Check your email for password reset instructions, 5) Follow the link to create a new password. If you don''t receive the email, check your spam folder.', 6, 'reset password, forgot password, change password, password recovery', 10, true, NOW(), NOW()),
('Can I change my email address?', 'Yes! You can change your email address in your account settings. Go to your profile, click on "Account Settings", and update your email. You may need to verify the new email address before it becomes active.', 6, 'change email, update email, email address, modify email', 9, true, NOW(), NOW()),
('How do I update my profile?', 'To update your profile: 1) Log in to your account, 2) Click on your profile icon in the top navigation, 3) Select "Profile" from the menu, 4) Edit your information including name, bio, profile picture, and other details, 5) Click "Save" to update your profile.', 6, 'update profile, edit profile, profile settings, change profile', 9, true, NOW(), NOW()),
('Can I delete my account?', 'Yes, you can delete your account. Go to your account settings, scroll to the "Account" section, and click "Delete Account". Please note that account deletion is permanent and you will lose access to all your enrolled courses and progress. Contact support if you need assistance.', 6, 'delete account, remove account, close account, account deletion', 8, true, NOW(), NOW()),
('Why can''t I log in?', 'If you can''t log in, try these steps: 1) Verify you''re using the correct email and password, 2) Check if Caps Lock is on, 3) Try resetting your password, 4) Clear your browser cache and cookies, 5) Try a different browser, 6) Contact support if the issue persists.', 6, 'cannot login, login problem, login issue, access account', 9, true, NOW(), NOW()),
('Do I need to verify my email?', 'Email verification is recommended but not always required. Verifying your email helps secure your account and allows you to receive important notifications, password reset links, and course updates. Check your inbox (and spam folder) for a verification email after registration.', 6, 'verify email, email verification, confirm email, email confirmation', 8, true, NOW(), NOW()),
('Can I have multiple accounts?', 'We recommend having only one account per person. Having multiple accounts may violate our terms of service. If you need to merge accounts or have a legitimate reason for multiple accounts, please contact our support team for assistance.', 6, 'multiple accounts, two accounts, duplicate account, merge accounts', 7, true, NOW(), NOW()),
('How do I change my username?', 'Your username is typically your email address or display name. You can change your display name in your profile settings. Go to Profile > Edit Profile and update your name. Note that your email address used for login cannot be changed easily - contact support if needed.', 6, 'change username, update username, modify username, display name', 7, true, NOW(), NOW()),

-- 7. CERTIFICATES (CategoryId = 7)
('How do I get my certificate?', 'To get your certificate: 1) Complete all course requirements including lessons, assignments, and quizzes, 2) Achieve the minimum passing grade if required, 3) Your certificate will be automatically generated, 4) Go to your Dashboard, 5) Find the completed course and click "Download Certificate".', 7, 'get certificate, obtain certificate, download certificate, receive certificate', 10, true, NOW(), NOW()),
('Are certificates verified?', 'Yes! Certificates from paid courses include verification features. Employers and others can verify your certificate using the certificate number or verification link. Free course certificates may have basic verification depending on the course.', 7, 'verified certificate, certificate verification, verify certificate, certificate validation', 9, true, NOW(), NOW()),
('Can I add my certificate to LinkedIn?', 'Absolutely! You can add your certificate to LinkedIn: 1) Download your certificate, 2) Go to your LinkedIn profile, 3) Add it to the "Licenses & Certifications" section, 4) Include the certificate name, issuing organization (AUNG), and certificate number. This helps showcase your achievements to employers.', 7, 'linkedin certificate, add to linkedin, share certificate linkedin, certificate linkedin', 9, true, NOW(), NOW()),
('What information is on the certificate?', 'Certificates typically include: your name, course title, completion date, certificate number, instructor name, AUNG logo, and verification information. The exact format may vary by course, but all certificates are professionally designed and include verification details.', 7, 'certificate information, what on certificate, certificate details, certificate content', 8, true, NOW(), NOW()),
('Can I get a physical certificate?', 'Currently, we provide digital certificates that you can download and print. Physical certificates may be available for certain courses or as a premium option. Contact support to inquire about physical certificate availability for specific courses.', 7, 'physical certificate, printed certificate, hard copy certificate, paper certificate', 7, true, NOW(), NOW()),
('Do free courses offer certificates?', 'Some free courses offer certificates upon completion, while others may not. Certificate availability is indicated on each course page. Paid courses typically include verified certificates with additional features like verification codes and digital signatures.', 7, 'free course certificate, certificate free course, free certificate', 8, true, NOW(), NOW()),
('How long is my certificate valid?', 'Your certificate does not expire and remains valid indefinitely. However, course content and industry standards may evolve over time. We recommend keeping your skills updated by taking advanced or updated courses in your field.', 7, 'certificate validity, certificate expiration, certificate expiry, how long valid', 7, true, NOW(), NOW()),
('Can I re-download my certificate?', 'Yes! You can re-download your certificate anytime. Go to your Dashboard, find the completed course, and click "Download Certificate". Your certificates are permanently stored in your account, so you can access them whenever needed.', 7, 'redownload certificate, download again, get certificate again, certificate access', 8, true, NOW(), NOW()),

-- 8. TECHNICAL (CategoryId = 8)
('The website is not loading', 'If the website is not loading: 1) Check your internet connection, 2) Try refreshing the page (Ctrl+F5 or Cmd+Shift+R), 3) Clear your browser cache and cookies, 4) Try a different browser, 5) Disable browser extensions temporarily, 6) Check if the site is down for maintenance. Contact support if the issue persists.', 8, 'website not loading, site down, page not loading, loading issue', 10, true, NOW(), NOW()),
('Videos are not playing', 'If videos won''t play: 1) Check your internet connection speed, 2) Try a different browser (Chrome, Firefox, Safari, Edge), 3) Update your browser to the latest version, 4) Clear browser cache and cookies, 5) Disable ad blockers or extensions, 6) Try lowering video quality if available, 7) Check if JavaScript is enabled. Contact support if problems continue.', 8, 'video not playing, video issue, video problem, playback error', 9, true, NOW(), NOW()),
('I can''t upload files', 'If you can''t upload files: 1) Check file size limits (usually shown on upload page), 2) Verify file format is accepted, 3) Check your internet connection, 4) Try a different browser, 5) Clear browser cache, 6) Ensure you have sufficient storage/quota. Contact support with file details if the issue persists.', 8, 'upload problem, file upload issue, cannot upload, upload error', 9, true, NOW(), NOW()),
('The page keeps refreshing', 'If pages keep refreshing: 1) Clear your browser cache and cookies, 2) Disable browser extensions one by one to find conflicts, 3) Try incognito/private browsing mode, 4) Update your browser, 5) Check for JavaScript errors in browser console, 6) Try a different browser. Contact support with browser details if needed.', 8, 'page refreshing, auto refresh, page reloading, refresh issue', 8, true, NOW(), NOW()),
('I''m getting error messages', 'If you see error messages: 1) Note the exact error message and code, 2) Try refreshing the page, 3) Clear browser cache, 4) Check your internet connection, 5) Try a different browser, 6) Log out and log back in. If the error persists, contact support with the error details and what you were doing when it occurred.', 8, 'error message, error code, bug, technical error, system error', 9, true, NOW(), NOW()),
('My progress is not saving', 'If progress isn''t saving: 1) Ensure you''re logged in, 2) Check your internet connection, 3) Complete lessons fully (don''t close browser mid-lesson), 4) Refresh the page and check again, 5) Clear browser cache, 6) Try a different browser. Contact support if progress continues not to save.', 8, 'progress not saving, progress lost, save issue, progress problem', 9, true, NOW(), NOW()),
('The site is slow', 'If the site is slow: 1) Check your internet connection speed, 2) Close other browser tabs and applications, 3) Clear browser cache and cookies, 4) Try a different browser, 5) Disable browser extensions, 6) Check if your device meets minimum requirements. Contact support if slowness persists.', 8, 'slow site, slow loading, performance issue, lag, slow speed', 8, true, NOW(), NOW()),
('I can''t access my enrolled courses', 'If you can''t access enrolled courses: 1) Ensure you''re logged in with the correct account, 2) Check "My Courses" section in your Dashboard, 3) Verify course enrollment status, 4) Clear browser cache, 5) Try a different browser, 6) Contact support with course details if access is still denied.', 8, 'cannot access course, course access denied, enrolled course access', 9, true, NOW(), NOW()),

-- 9. ACCESS & DEVICES (CategoryId = 9)
('What browsers are supported?', 'AUNG works best with modern browsers including Google Chrome (latest version), Mozilla Firefox (latest version), Microsoft Edge (latest version), Safari (latest version), and Opera. We recommend keeping your browser updated for the best experience and security.', 9, 'browser support, supported browsers, which browser, browser compatibility', 10, true, NOW(), NOW()),
('Can I use AUNG on my phone?', 'Yes! AUNG is fully responsive and works on mobile phones, tablets, and desktops. You can access all features including courses, videos, assignments, and progress tracking through your mobile browser. We recommend using Chrome or Safari on mobile devices.', 9, 'mobile phone, phone access, smartphone, mobile device', 10, true, NOW(), NOW()),
('Do I need an app?', 'No app is required! AUNG works through your web browser on any device. Simply visit our website and log in. We are optimized for mobile browsers, so you get a great experience without needing to download anything. A mobile app may be available in the future.', 9, 'app needed, mobile app, application, download app', 9, true, NOW(), NOW()),
('What devices can I use?', 'You can use AUNG on: Desktop computers (Windows, Mac, Linux), Laptops, Tablets (iPad, Android tablets), Smartphones (iPhone, Android phones), and any device with a modern web browser and internet connection. All devices are supported!', 9, 'devices, compatible devices, which devices, device support', 9, true, NOW(), NOW()),
('Do I need special software?', 'No special software is needed! AUNG works through your web browser. You only need: a modern web browser (Chrome, Firefox, Safari, Edge), an internet connection, and JavaScript enabled. That''s it! No downloads or installations required.', 9, 'software needed, special software, requirements, system requirements', 9, true, NOW(), NOW()),
('Can I use AUNG offline?', 'Currently, AUNG requires an internet connection to access courses and materials. However, some courses may allow you to download materials (PDFs, code files) for offline reference. Video lessons require an online connection for streaming.', 9, 'offline access, without internet, offline mode, download for offline', 8, true, NOW(), NOW()),
('What screen resolution do I need?', 'AUNG is responsive and works on any screen size from mobile phones to large desktop monitors. We recommend a minimum screen width of 320px for mobile devices. For the best experience, use a screen resolution of 1280x720 or higher on desktop.', 9, 'screen resolution, display size, screen size, resolution requirements', 7, true, NOW(), NOW()),
('Does AUNG work on tablets?', 'Yes! AUNG works excellently on tablets including iPad, Android tablets, and Windows tablets. The interface automatically adapts to tablet screens, providing an optimal learning experience. You can watch videos, complete assignments, and track progress on tablets.', 9, 'tablet, ipad, android tablet, tablet support', 8, true, NOW(), NOW()),

-- 10. CAREER & JOBS (CategoryId = 10)
('Will these courses help my career?', 'Absolutely! AUNG courses are designed to help you advance your career by teaching practical, industry-relevant skills. Many students use our courses to: get promoted, switch careers, start freelancing, improve job performance, and stay competitive in their field. Our courses focus on real-world applications.', 10, 'career help, career advancement, job help, career growth, professional development', 10, true, NOW(), NOW()),
('Can I put AUNG courses on my resume?', 'Yes! You can and should include completed AUNG courses on your resume. List them in your "Education" or "Professional Development" section. Include: course name, completion date, and key skills learned. You can also add certificates to your LinkedIn profile for better visibility.', 10, 'resume, cv, job application, add to resume, resume courses', 10, true, NOW(), NOW()),
('Do employers recognize AUNG certificates?', 'Yes! Many employers recognize and value online learning certificates, especially when they demonstrate relevant skills. AUNG certificates show your commitment to continuous learning and skill development. Include certificates in job applications and LinkedIn profiles to showcase your qualifications.', 10, 'employer recognition, certificate recognition, job recognition, employer value', 9, true, NOW(), NOW()),
('What jobs can I get after completing courses?', 'Course completion can help you qualify for various roles depending on what you study. For example: Programming courses can lead to Software Developer roles, Web Development courses to Frontend/Backend Developer positions, Data Science courses to Data Analyst roles, and Business courses to various business positions. Check course descriptions for career outcomes.', 10, 'jobs after courses, career outcomes, job opportunities, what jobs', 9, true, NOW(), NOW()),
('Will I get job placement help?', 'While AUNG focuses on skill development through courses, we provide career resources including resume tips, interview preparation guidance, and job search strategies. Some courses may include career guidance modules. Check individual course descriptions for career support features.', 10, 'job placement, job help, career services, job assistance, placement', 8, true, NOW(), NOW()),
('How do courses help with freelancing?', 'AUNG courses teach practical skills that are highly valuable for freelancing. Many freelancers use our courses to: learn new skills, improve existing skills, stay updated with industry trends, and build portfolios. Courses in Web Development, Design, and Business are particularly useful for freelancers.', 10, 'freelancing, freelance, self-employed, freelance skills', 8, true, NOW(), NOW()),
('Can I use courses for professional development?', 'Absolutely! AUNG courses are perfect for professional development. Many professionals use our platform to: upskill for promotions, learn new technologies, stay competitive, meet continuing education requirements, and expand their skill set. Courses are designed for working professionals.', 10, 'professional development, career development, skill development, upskilling', 9, true, NOW(), NOW()),
('Do courses count for continuing education credits?', 'Some courses may qualify for continuing education credits depending on your profession and requirements. Check with your professional organization or employer about credit acceptance. We provide completion certificates that can be submitted for credit consideration.', 10, 'continuing education, ce credits, professional credits, education credits', 7, true, NOW(), NOW()),

-- 11. COMMUNITY (CategoryId = 11)
('Is there a student community?', 'Yes! AUNG has an active learning community. You can interact with other students through: course discussion forums, Q&A sections within courses, course messaging, and community features. Many students form study groups and help each other learn.', 11, 'student community, community, learners, students, discussion', 9, true, NOW(), NOW()),
('Can I ask questions to other students?', 'Absolutely! You can ask questions and get help from other students in course discussion forums and Q&A sections. Many courses have active communities where students help each other, share resources, and discuss course materials. Participation is encouraged!', 11, 'ask questions, student questions, discussion forum, student help', 9, true, NOW(), NOW()),
('Are there study groups?', 'While AUNG doesn''t officially organize study groups, students often form informal study groups through course discussions. You can connect with classmates, share study materials, and collaborate on projects. Check course discussion forums to find study partners.', 11, 'study groups, study partners, group learning, collaborate', 8, true, NOW(), NOW()),
('Can I share my projects?', 'Yes! Many courses encourage sharing projects and assignments. You can share your work in course discussion forums, get feedback from instructors and peers, and showcase your learning. Some courses have dedicated project showcase sections.', 11, 'share projects, project sharing, showcase work, share assignments', 8, true, NOW(), NOW()),
('How do I connect with other learners?', 'You can connect with other learners through: course discussion forums, course Q&A sections, course messaging features, and by participating actively in course activities. Engaging with the community enhances your learning experience and helps you build a professional network.', 11, 'connect learners, network, meet students, connect with peers', 8, true, NOW(), NOW()),
('Is there a forum or discussion board?', 'Yes! Each course typically has its own discussion forum where you can: ask questions, share insights, discuss course materials, get help from peers, and interact with instructors. Forums are a great way to enhance your learning and connect with others.', 11, 'forum, discussion board, discussion forum, community forum', 9, true, NOW(), NOW()),
('Can instructors see my discussions?', 'Yes, instructors can see and participate in course discussions. They often monitor forums to answer questions, provide guidance, and ensure a positive learning environment. Your participation in discussions can also help instructors understand how to improve courses.', 11, 'instructor see discussions, instructor forum, instructor participation', 7, true, NOW(), NOW()),

-- 12. LEGAL & PRIVACY (CategoryId = 12)
('What is your privacy policy?', 'AUNG takes your privacy seriously. We collect and use your information only to provide and improve our services. We never sell your personal data to third parties. Your course progress, enrollment data, and personal information are protected. Review our full Privacy Policy in the website footer for complete details.', 12, 'privacy policy, data privacy, privacy, personal data', 10, true, NOW(), NOW()),
('How do you protect my data?', 'We protect your data using: industry-standard encryption for data transmission, secure servers with regular security updates, access controls limiting who can view your data, regular security audits, and compliance with data protection regulations. Your information is stored securely and accessed only by authorized personnel.', 12, 'data protection, data security, protect data, secure data, data safety', 10, true, NOW(), NOW()),
('What information do you collect?', 'We collect information you provide (name, email, profile information), course enrollment and progress data, payment information (processed securely through payment gateways), usage data (to improve our platform), and device information (for technical support). We only collect what''s necessary to provide our services.', 12, 'information collected, data collected, what data, personal information', 9, true, NOW(), NOW()),
('Can I delete my data?', 'Yes! You can delete your account and associated data at any time through your account settings. Account deletion is permanent and removes your personal information, course enrollments, and progress. Some data may be retained for legal or business purposes as outlined in our Privacy Policy.', 12, 'delete data, remove data, data deletion, erase data', 9, true, NOW(), NOW()),
('Do you share my information?', 'We do not sell your personal information. We may share data with: trusted service providers who help us operate (under strict confidentiality), payment processors for transactions, legal authorities if required by law, and with your consent for specific purposes. We never share data for marketing by third parties.', 12, 'share information, data sharing, third party, sell data', 9, true, NOW(), NOW()),
('What are your terms of service?', 'Our Terms of Service outline: acceptable use of the platform, user responsibilities, intellectual property rights, payment terms, refund policies, account termination procedures, and dispute resolution. You can review the complete Terms of Service in the website footer or by contacting support.', 12, 'terms of service, terms, user agreement, legal terms', 9, true, NOW(), NOW()),
('Can I use course materials commercially?', 'Course materials are for personal learning use only. You cannot: redistribute course content, sell course materials, use content for commercial training without permission, or violate instructor copyrights. Check individual course terms for specific usage rights. Contact us for commercial licensing inquiries.', 12, 'commercial use, copyright, course materials use, redistribute content', 8, true, NOW(), NOW()),
('What is your refund policy?', 'We offer refunds for paid courses within the refund period (typically 30 days from purchase). Refund requests can be made through your account settings or by contacting support. Refunds are processed to your original payment method. See our Terms of Service for complete refund policy details.', 12, 'refund policy, money back, return policy, refund terms', 9, true, NOW(), NOW()),
('How do you handle cookies?', 'We use cookies to: remember your login status, improve website functionality, analyze site usage, and personalize your experience. You can control cookies through your browser settings. Essential cookies are required for the site to function. See our Privacy Policy for detailed cookie information.', 12, 'cookies, cookie policy, tracking, browser cookies', 8, true, NOW(), NOW()),
('Is my payment information secure?', 'Yes! We use industry-standard encryption and secure payment gateways. We never store your full credit card details on our servers. All payments are processed through PCI-compliant payment processors. Your financial information is protected with the same security standards used by major banks.', 12, 'payment security, secure payment, financial security, payment protection', 10, true, NOW(), NOW()),

-- 13. INTRODUCTION (CategoryId = 13)
('Hello', 'Hello! Welcome to AUNG (Advanced Upskilling & New Growth)! 👋 I''m here to help you learn about our platform, courses, instructors, and services. Feel free to ask me anything - I can help with questions about navigation, courses, payments, learning, and more. What would you like to know?', 13, 'hello, hi, hey, greetings, welcome, start', 10, true, NOW(), NOW()),
('Hi', 'Hi there! 👋 Welcome to AUNG! I''m your virtual assistant ready to help you discover everything about our learning platform. Whether you''re new here or looking for specific information, I''m here to assist. What can I help you with today?', 13, 'hi, hello, hey, greetings, welcome, start', 10, true, NOW(), NOW()),
('Hey', 'Hey! 👋 Great to see you! Welcome to AUNG (Advanced Upskilling & New Growth). I can answer questions about our platform, help you find courses, explain how to get started, and assist with any other questions you might have. What would you like to know?', 13, 'hey, hello, hi, greetings, welcome, start', 10, true, NOW(), NOW()),
('Start', 'Welcome to AUNG! 🚀 I''m here to help you get started. You can ask me about: our learning platform, available courses, instructors, how to enroll, payment options, or anything else you''d like to know. What interests you most?', 13, 'start, begin, getting started, new user, first time', 10, true, NOW(), NOW()),
('Help', 'I''m here to help! 💡 I can assist you with questions about: 📚 Our platform and services, 👨‍🏫 Instructors and courses, 💳 Payment and enrollment, 🚀 Getting started with learning, and much more! What do you need help with?', 13, 'help, assistance, support, need help, can you help', 10, true, NOW(), NOW()),

-- 14. CONCLUSION (CategoryId = 14)
('Goodbye', 'Thank you for chatting with me! 👋 I hope I was able to help you learn more about AUNG. If you have more questions later, feel free to come back anytime. Good luck with your learning journey! Happy learning! 🌟', 14, 'goodbye, bye, see you, farewell, exit, end chat', 10, true, NOW(), NOW()),
('Bye', 'Bye! 👋 Thanks for visiting AUNG! I hope you found the information you were looking for. Remember, you can always come back if you have more questions. Best of luck with your learning! Take care! 🌟', 14, 'bye, goodbye, see you, farewell, exit, end chat', 10, true, NOW(), NOW()),
('Thank you', 'You''re very welcome! 😊 I''m glad I could help. If you have any more questions about AUNG, courses, or learning, don''t hesitate to ask. Good luck with your learning journey, and I hope to chat with you again soon! 🌟', 14, 'thank you, thanks, appreciate, grateful, thank', 10, true, NOW(), NOW()),
('Thanks', 'You''re welcome! 😊 Happy to help! If you need anything else about AUNG or our courses, just ask. Wishing you success in your learning journey. Feel free to come back anytime! 🌟', 14, 'thanks, thank you, appreciate, grateful, thank', 10, true, NOW(), NOW()),
('End chat', 'Thank you for using AUNG''s chat support! 👋 I hope I was helpful. If you have more questions in the future, I''ll be here to assist. Good luck with your learning journey, and remember - we''re here to support your growth! 🌟', 14, 'end chat, close chat, finish, done, end conversation', 10, true, NOW(), NOW()),
('Done', 'Great! I''m glad I could assist you today. 😊 If you have any more questions about AUNG, courses, or learning, feel free to come back. Best wishes for your learning journey! Happy learning! 🌟', 14, 'done, finished, complete, all done, that''s all', 9, true, NOW(), NOW()),
('That''s all', 'Perfect! Thanks for chatting with me! 👋 I hope you found everything you needed. If you think of any other questions later, don''t hesitate to ask. Good luck with your learning, and I hope to help you again soon! 🌟', 14, 'that''s all, all done, nothing else, finished, complete', 9, true, NOW(), NOW())

) AS new_faqs("Question", "Answer", "CategoryId", "Keywords", "Priority", "IsActive", "CreatedAt", "UpdatedAt")
WHERE NOT EXISTS (
    SELECT 1 FROM "FAQs" 
    WHERE LOWER(TRIM("Question")) = LOWER(TRIM(new_faqs."Question"))
);

-- Update existing FAQs in these categories if they exist
UPDATE "FAQs" f
SET 
    "Answer" = new_data."Answer",
    "CategoryId" = new_data."CategoryId",
    "Keywords" = new_data."Keywords",
    "Priority" = new_data."Priority",
    "UpdatedAt" = NOW()
FROM (VALUES
-- Account updates
('How do I reset my password?', 'To reset your password: 1) Click "Login" in the navigation bar, 2) Click "Forgot Password" link, 3) Enter your email address, 4) Check your email for password reset instructions, 5) Follow the link to create a new password. If you don''t receive the email, check your spam folder.', 6, 'reset password, forgot password, change password, password recovery', 10),
-- Certificate updates  
('How do I get my certificate?', 'To get your certificate: 1) Complete all course requirements including lessons, assignments, and quizzes, 2) Achieve the minimum passing grade if required, 3) Your certificate will be automatically generated, 4) Go to your Dashboard, 5) Find the completed course and click "Download Certificate".', 7, 'get certificate, obtain certificate, download certificate, receive certificate', 10),
-- Technical updates
('The website is not loading', 'If the website is not loading: 1) Check your internet connection, 2) Try refreshing the page (Ctrl+F5 or Cmd+Shift+R), 3) Clear your browser cache and cookies, 4) Try a different browser, 5) Disable browser extensions temporarily, 6) Check if the site is down for maintenance. Contact support if the issue persists.', 8, 'website not loading, site down, page not loading, loading issue', 10),
-- Access & Devices updates
('What browsers are supported?', 'AUNG works best with modern browsers including Google Chrome (latest version), Mozilla Firefox (latest version), Microsoft Edge (latest version), Safari (latest version), and Opera. We recommend keeping your browser updated for the best experience and security.', 9, 'browser support, supported browsers, which browser, browser compatibility', 10),
-- Career & Jobs updates
('Will these courses help my career?', 'Absolutely! AUNG courses are designed to help you advance your career by teaching practical, industry-relevant skills. Many students use our courses to: get promoted, switch careers, start freelancing, improve job performance, and stay competitive in their field. Our courses focus on real-world applications.', 10, 'career help, career advancement, job help, career growth, professional development', 10),
-- Community updates
('Is there a student community?', 'Yes! AUNG has an active learning community. You can interact with other students through: course discussion forums, Q&A sections within courses, course messaging, and community features. Many students form study groups and help each other learn.', 11, 'student community, community, learners, students, discussion', 9),
-- Legal & Privacy updates
('What is your privacy policy?', 'AUNG takes your privacy seriously. We collect and use your information only to provide and improve our services. We never sell your personal data to third parties. Your course progress, enrollment data, and personal information are protected. Review our full Privacy Policy in the website footer for complete details.', 12, 'privacy policy, data privacy, privacy, personal data', 10),
-- Introduction updates
('Hello', 'Hello! Welcome to AUNG (Advanced Upskilling & New Growth)! 👋 I''m here to help you learn about our platform, courses, instructors, and services. Feel free to ask me anything - I can help with questions about navigation, courses, payments, learning, and more. What would you like to know?', 13, 'hello, hi, hey, greetings, welcome, start', 10),
-- Conclusion updates
('Goodbye', 'Thank you for chatting with me! 👋 I hope I was able to help you learn more about AUNG. If you have more questions later, feel free to come back anytime. Good luck with your learning journey! Happy learning! 🌟', 14, 'goodbye, bye, see you, farewell, exit, end chat', 10)
) AS new_data("Question", "Answer", "CategoryId", "Keywords", "Priority")
WHERE LOWER(TRIM(f."Question")) = LOWER(TRIM(new_data."Question"));
